using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Testably.Abstractions.Tests.SourceGenerator;

public class GlobalGenerator
{
	public void GenerateClass(GeneratorExecutionContext context)
	{
		StringBuilder sourceBuilder = GetSourceBuilder();
		GenerateSource(sourceBuilder);
		string fileName = "DatabaseCollection.cs";
		context.AddSource(fileName,
			SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
	}

	private void GenerateSource(StringBuilder sourceBuilder)
		=> sourceBuilder.Append(@"
using Xunit;

namespace Testably.Abstractions.TestHelpers.Settings;

[CollectionDefinition(""RealFileSystemTests"")]
public class DatabaseCollection : ICollectionFixture<RealFileSystemFixture>
{
	// This class has no code, and is never created. Its purpose is simply
	// to be the place to apply [CollectionDefinition] and all the
	// ICollectionFixture<> interfaces.
}");

	private StringBuilder GetSourceBuilder()
		=> new(
			@"//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by ""Testably.Abstractions.Tests.SourceGenerator"".
// 
//   Changes to this file may cause incorrect behavior
//   and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
");
}
