using AutoFixture;
using AutoFixture.Kernel;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Testably.Abstractions.TestHelpers;

/// <summary>
///     Provides a data source for a data theory, with the data coming from inline
///     values combined with auto-generated data specimens generated by AutoFixture.
/// </summary>
public class AutoArgumentsAttribute : UntypedDataSourceGeneratorAttribute
{
	/// <summary>
	///     Gets the fixture factory.
	/// </summary>
	private readonly Func<IFixture> _fixtureFactory;

	/// <summary>
	///     Gets the data values to pass to the theory.
	/// </summary>
	private readonly object?[] _values;

	/// <summary>
	///     Initializes a new instance of the <see cref="AutoArgumentsAttribute" /> class.
	/// </summary>
	public AutoArgumentsAttribute(params object?[] values)
		: this(() => new Fixture(), values)
	{
	}

	/// <summary>
	///     Initializes a new instance of the <see cref="AutoArgumentsAttribute" /> class.
	/// </summary>
	protected AutoArgumentsAttribute(Func<IFixture> fixtureFactory, params object?[]? values)
	{
		_fixtureFactory = fixtureFactory ?? throw new ArgumentNullException(nameof(fixtureFactory));
		_values = values ?? [null,];
	}

	/// <inheritdoc />
	protected override IEnumerable<Func<object?[]?>> GenerateDataSources(
		DataGeneratorMetadata dataGeneratorMetadata)
	{
		if (dataGeneratorMetadata.TestInformation is not null)
		{
			IFixture fixture = _fixtureFactory();
			yield return ()
				=> _values.Concat(dataGeneratorMetadata.TestInformation.Parameters
					.Skip(_values.Length)
					.Select(x => fixture.Create(x.Type, new SpecimenContext(fixture)))).ToArray();
		}
	}
}
