name: "Pull Request"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  contents: read

jobs:
  main:
    permissions:
      pull-requests: read
      statuses: write
    name: Ensure Conventional Commit spec
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            doc
            refactor
          scopes: |
            file
            time
          requireScope: false
